spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auction?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
eureka:
  client:
    enabled: false
